### ISSUE TITLE
Runtime error - integer divide by zero

### ISSUE THREAD

**Issue by benjaminlewis-1000** [gphotosuploader/gphotos-uploader-cli#239]
Hi,

I've had this configured and running properly for a few months now, but recently I've been getting an issue. After scanning through a portion of my library, the script jerks to a halt with the following error message: 

```
2020/10/04 08:44:53 Uploading content to 'https://photoslibrary.googleapis.com/v1/uploads?upload_id=ABg5-Uy1xOJfON9H1XkqtiDRgPKQeRNkpWVksW3FLq2Wwf2a24IMRL3aNBOVSRp_2-hMMz2W0TfoyfXr4wIRoQp11QY&upload_protocol=resumable'
2020/10/04 08:44:53 already uploaded: <<<Anonymized file path>>>: skipping file...
panic: runtime error: integer divide by zero

goroutine 51 [running]:
github.com/gphotosuploader/google-photos-api-client-go/lib-gphotos.(*ReadProgressReporter).report(0xc001d2a000)
        <<<$HOME>>>/Projects/Proj1/pkg/mod/github.com/gphotosuploader/google-photos-api-client-go@v1.0.4/lib-gphotos/progress.go:27 +0x212
github.com/gphotosuploader/google-photos-api-client-go/lib-gphotos.(*ReadProgressReporter).Read(0xc001d2a000, 0xc001fac000, 0x4000, 0x4000, 0xc0005aae80, 0x20, 0xc0005aae78)
        <<<$HOME>>>/Projects/Proj1/pkg/mod/github.com/gphotosuploader/google-photos-api-client-go@v1.0.4/lib-gphotos/progress.go:22 +0x8e
net/http.(*http2clientStream).writeRequestBody(0xc001bfe000, 0x7f5935d31868, 0xc001fa0010, 0x7f5935d31888, 0xc001fa0010, 0x0, 0x0)
        /usr/local/go/src/net/http/h2_bundle.go:7664 +0x521
net/http.(*http2Transport).getBodyWriterState.func1()
        /usr/local/go/src/net/http/h2_bundle.go:8878 +0xc2
created by net/http.http2bodyWriterState.scheduleBodyWrite
        /usr/local/go/src/net/http/h2_bundle.go:8925 +0xa3
````

The last  file checked is different every time, so I believe it's not choking on a specific file.  If relevant, I've got ~130k photos that the script goes through. Happy to provide other information as well.

**Comment by pacoorozco** [comment]
Hi @benjaminlewis-1000 

**Have you tried the last available version of `gphotos-uploader-cli`?** It solves some bugs (including some related with the `ReadProgress`).

**Comment by benjaminlewis-1000** [comment]
Good point. I'll try it in the next few days. Thanks!

**Comment by pacoorozco** [comment]
Did it work @benjaminlewis-1000 ?

**Comment by benjaminlewis-1000** [comment]
Yes, thank you!
